import type { User, Post, Listing, Comment, Conversation, Group, Notification, ApprovalPost } from './types'

// Mock Users
export const mockUsers: User[] = [
  {
    id: '1',
    name: 'أحمد محمد',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=ahmed',
    bio: 'وسيط عقاري معتمد | خبرة ١٠ سنوات في سوق العقارات المصري',
    city: 'القاهرة',
    role: 'agent',
    tier: 2,
    isVerified: true,
    followers: 1250,
    following: 340,
    posts: 89,
    rating: 4.8,
    reviewCount: 127,
    responseTime: 'يرد خلال ساعة',
    phone: '+201234567890',
  },
  {
    id: '2',
    name: 'سارة علي',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=sara',
    bio: 'مهتمة بالاستثمار العقاري',
    city: 'الجيزة',
    role: 'buyer',
    tier: 3,
    isVerified: false,
    followers: 45,
    following: 120,
    posts: 12,
  },
  {
    id: '3',
    name: 'محمد حسن',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=mohamed',
    bio: 'صاحب شركة عقارات | متخصص في العقارات الفاخرة',
    city: 'القاهرة الجديدة',
    role: 'seller',
    tier: 2,
    isVerified: true,
    followers: 3200,
    following: 180,
    posts: 156,
    rating: 4.9,
    reviewCount: 89,
    responseTime: 'يرد خلال ٣٠ دقيقة',
  },
  {
    id: '4',
    name: 'فاطمة أحمد',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=fatma',
    bio: 'أبحث عن شقة للإيجار في المعادي',
    city: 'القاهرة',
    role: 'interested',
    tier: 4,
    isVerified: false,
    followers: 12,
    following: 89,
    posts: 3,
  },
  {
    id: '5',
    name: 'يوسف كريم',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=youssef',
    bio: 'مدير مبيعات | شركة الأهرام للتطوير العقاري',
    city: 'الإسكندرية',
    role: 'agent',
    tier: 1,
    isVerified: true,
    followers: 8500,
    following: 420,
    posts: 312,
    rating: 4.7,
    reviewCount: 256,
    responseTime: 'يرد خلال ١٥ دقيقة',
  },
]

export const currentUser: User = mockUsers[0]

// Mock Listings
export const mockListings: Listing[] = [
  {
    id: '1',
    title: 'شقة فاخرة بالتجمع الخامس',
    price: 3500000,
    currency: 'EGP',
    type: 'apartment',
    purpose: 'sale',
    location: {
      city: 'القاهرة',
      area: 'التجمع الخامس',
      address: 'شارع التسعين الجنوبي',
    },
    specs: {
      bedrooms: 3,
      bathrooms: 2,
      area: 180,
    },
    features: {
      finishing: 'finished',
      floor: 5,
      furnished: false,
    },
    description: 'شقة فاخرة بموقع متميز في التجمع الخامس، تشطيب سوبر لوكس، قريبة من جميع الخدمات. الشقة بها ٣ غرف نوم و٢ حمام وريسبشن كبير ومطبخ مجهز. العمارة بها أمن وجراج خاص.',
    images: [
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800',
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
      'https://images.unsplash.com/photo-1560185893-a55cbc8c57e8?w=800',
    ],
    agent: mockUsers[0],
    views: 234,
    createdAt: '2024-01-15',
  },
  {
    id: '2',
    title: 'فيلا مستقلة في الشيخ زايد',
    price: 12000000,
    currency: 'EGP',
    type: 'villa',
    purpose: 'sale',
    location: {
      city: 'الجيزة',
      area: 'الشيخ زايد',
      address: 'كمبوند بيفرلي هيلز',
    },
    specs: {
      bedrooms: 5,
      bathrooms: 4,
      area: 450,
    },
    features: {
      finishing: 'finished',
      furnished: true,
    },
    description: 'فيلا مستقلة فاخرة في أرقى كمبوندات الشيخ زايد، بها حمام سباحة خاص وحديقة كبيرة. الفيلا مؤثثة بالكامل بأثاث راقي.',
    images: [
      'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800',
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800',
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800',
    ],
    agent: mockUsers[2],
    views: 567,
    createdAt: '2024-01-10',
  },
  {
    id: '3',
    title: 'استوديو للإيجار في المعادي',
    price: 8000,
    currency: 'EGP',
    type: 'studio',
    purpose: 'rent',
    location: {
      city: 'القاهرة',
      area: 'المعادي',
      address: 'شارع ٩',
    },
    specs: {
      bedrooms: 1,
      bathrooms: 1,
      area: 55,
    },
    features: {
      finishing: 'finished',
      floor: 3,
      furnished: true,
    },
    description: 'استوديو مفروش بالكامل في المعادي، مناسب للأفراد أو الطلاب. قريب من المترو والخدمات.',
    images: [
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800',
      'https://images.unsplash.com/photo-1560185127-6ed189bf02f4?w=800',
    ],
    agent: mockUsers[0],
    views: 123,
    createdAt: '2024-01-18',
  },
  {
    id: '4',
    title: 'دوبلكس في مدينتي',
    price: 5800000,
    currency: 'EGP',
    type: 'duplex',
    purpose: 'sale',
    location: {
      city: 'القاهرة',
      area: 'مدينتي',
    },
    specs: {
      bedrooms: 4,
      bathrooms: 3,
      area: 280,
    },
    features: {
      finishing: 'semi-finished',
      floor: 8,
      furnished: false,
    },
    description: 'دوبلكس رائع بإطلالة مفتوحة على الحديقة، نصف تشطيب، موقع متميز في مدينتي.',
    images: [
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800',
      'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800',
    ],
    agent: mockUsers[4],
    views: 345,
    createdAt: '2024-01-12',
  },
]

// Mock Posts
export const mockPosts: Post[] = [
  {
    id: '1',
    author: mockUsers[0],
    content: 'نصيحة اليوم: قبل ما تشتري أي عقار، تأكد من صحة الأوراق والملكية. كتير ناس بتقع في مشاكل قانونية بسبب عدم التحقق. لو محتاج مساعدة في فحص الأوراق، أنا موجود! 📋✅',
    likes: 234,
    comments: 45,
    shares: 12,
    isLiked: false,
    isSaved: true,
    createdAt: 'منذ ساعتين',
    type: 'text',
  },
  {
    id: '2',
    author: mockUsers[2],
    content: 'شقة جديدة متاحة للبيع في التجمع الخامس! موقع ممتاز وسعر مناسب جداً. تواصلوا معايا للتفاصيل.',
    listing: mockListings[0],
    likes: 89,
    comments: 23,
    shares: 8,
    isLiked: true,
    isSaved: false,
    createdAt: 'منذ ٤ ساعات',
    type: 'listing',
  },
  {
    id: '3',
    author: mockUsers[1],
    content: 'أخيراً لقيت شقة أحلامي في المعادي! شكراً بيتكو على المنصة الرائعة دي. لو حد محتاج نصيحة عن منطقة المعادي، أنا تحت أمركم 🏠❤️',
    images: ['https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800'],
    likes: 156,
    comments: 67,
    shares: 4,
    isLiked: false,
    isSaved: false,
    createdAt: 'منذ يوم',
    type: 'image',
  },
  {
    id: '4',
    author: mockUsers[4],
    content: 'جولة في أحدث مشاريعنا في الإسكندرية! شقق بإطلالة على البحر مباشرة. شاهدوا الفيديو 🌊',
    video: 'https://example.com/video.mp4',
    likes: 567,
    comments: 123,
    shares: 45,
    isLiked: true,
    isSaved: true,
    createdAt: 'منذ يومين',
    type: 'video',
  },
  {
    id: '5',
    author: mockUsers[3],
    content: 'سؤال للخبراء: إيه رأيكم في الاستثمار في العاصمة الإدارية الجديدة دلوقتي؟ هل الوقت مناسب للشراء ولا نستنى؟',
    likes: 45,
    comments: 89,
    shares: 2,
    isLiked: false,
    isSaved: false,
    createdAt: 'منذ ٣ أيام',
    type: 'text',
  },
]

// Mock Comments
export const mockComments: Comment[] = [
  {
    id: '1',
    author: mockUsers[2],
    content: 'كلام صح جداً! أنا شخصياً وقعت في مشكلة كده قبل كده.',
    likes: 12,
    isLiked: false,
    createdAt: 'منذ ساعة',
    isPinned: true,
  },
  {
    id: '2',
    author: mockUsers[1],
    content: 'شكراً على النصيحة! ممكن تقولنا إيه أهم الأوراق اللي لازم نتأكد منها؟',
    likes: 8,
    isLiked: true,
    createdAt: 'منذ ٣٠ دقيقة',
    replies: [
      {
        id: '2-1',
        author: mockUsers[0],
        content: 'أهم حاجة: عقد الملكية المسجل، رخصة البناء، وشهادة الضرائب العقارية.',
        likes: 15,
        isLiked: false,
        createdAt: 'منذ ٢٠ دقيقة',
      },
    ],
  },
  {
    id: '3',
    author: mockUsers[3],
    content: 'ممكن حد يساعدني أفهم إيه الفرق بين العقد الابتدائي والعقد المسجل؟',
    likes: 3,
    isLiked: false,
    createdAt: 'منذ ١٥ دقيقة',
  },
]

// Mock Conversations
export const mockConversations: Conversation[] = [
  {
    id: '1',
    participant: mockUsers[2],
    listing: mockListings[0],
    lastMessage: 'أيوه الشقة لسه متاحة، تحب تيجي تشوفها؟',
    lastMessageTime: 'منذ ٥ دقائق',
    unreadCount: 2,
    type: 'listing',
  },
  {
    id: '2',
    participant: mockUsers[1],
    lastMessage: 'شكراً على المعلومات!',
    lastMessageTime: 'منذ ساعة',
    unreadCount: 0,
    type: 'direct',
  },
  {
    id: '3',
    participant: mockUsers[4],
    listing: mockListings[1],
    lastMessage: 'السعر قابل للتفاوض؟',
    lastMessageTime: 'منذ ٣ ساعات',
    unreadCount: 1,
    type: 'listing',
  },
]

// Mock Groups
export const mockGroups: Group[] = [
  {
    id: '1',
    name: 'عقارات القاهرة الجديدة',
    description: 'مجموعة متخصصة في عقارات القاهرة الجديدة والتجمع الخامس',
    coverImage: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800',
    memberCount: 12500,
    isJoined: true,
    rules: ['ممنوع الإعلانات المتكررة', 'احترام جميع الأعضاء', 'المحتوى العقاري فقط'],
  },
  {
    id: '2',
    name: 'نصائح الاستثمار العقاري',
    description: 'تبادل الخبرات والنصائح في مجال الاستثمار العقاري',
    coverImage: 'https://images.unsplash.com/photo-1560520653-9e0e4c89eb11?w=800',
    memberCount: 8900,
    isJoined: false,
  },
  {
    id: '3',
    name: 'إيجارات الإسكندرية',
    description: 'شقق وعقارات للإيجار في الإسكندرية',
    coverImage: 'https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800',
    memberCount: 5600,
    isJoined: true,
  },
]

// Mock Notifications
export const mockNotifications: Notification[] = [
  {
    id: '1',
    type: 'like',
    title: 'إعجابات جديدة',
    message: 'أحمد وسارة و٨ آخرين عملوا لايك على بوستك',
    users: [mockUsers[0], mockUsers[1]],
    isRead: false,
    createdAt: 'منذ ٥ دقائق',
  },
  {
    id: '2',
    type: 'comment',
    title: 'تعليق جديد',
    message: 'محمد حسن علق على بوستك: "كلام مهم جداً!"',
    users: [mockUsers[2]],
    isRead: false,
    createdAt: 'منذ ١٥ دقيقة',
  },
  {
    id: '3',
    type: 'follow',
    title: 'متابع جديد',
    message: 'فاطمة أحمد بدأت تتابعك',
    users: [mockUsers[3]],
    isRead: true,
    createdAt: 'منذ ساعة',
  },
  {
    id: '4',
    type: 'listing_match',
    title: 'عقار يناسبك',
    message: 'لقينا شقة تناسب بحثك في التجمع الخامس',
    listing: mockListings[0],
    isRead: true,
    createdAt: 'منذ ٣ ساعات',
  },
  {
    id: '5',
    type: 'price_drop',
    title: 'انخفاض سعر',
    message: 'الفيلا اللي حفظتها نزل سعرها ١٠٪',
    listing: mockListings[1],
    isRead: false,
    createdAt: 'منذ يوم',
  },
]

// Mock Approval Posts
export const mockApprovalPosts: ApprovalPost[] = [
  {
    id: '1',
    title: 'نصائح لشراء أول شقة',
    content: 'دليل شامل لكل اللي محتاج يعرفه قبل ما يشتري أول شقة...',
    status: 'pending',
    submittedAt: 'منذ ٢ ساعات',
  },
  {
    id: '2',
    title: 'تجربتي مع شراء عقار في الساحل',
    content: 'حبيت أشارككم تجربتي الشخصية...',
    status: 'approved',
    submittedAt: 'منذ يومين',
    publishedAt: 'منذ يوم',
    engagementStats: {
      likes: 45,
      comments: 12,
      views: 234,
    },
  },
  {
    id: '3',
    title: 'عرض خاص على شقق',
    content: 'خصم ٢٠٪ على كل الشقق...',
    status: 'rejected',
    submittedAt: 'منذ ٣ أيام',
    rejectionReason: 'المحتوى يحتوي على إعلان مباشر. يرجى إعادة الصياغة.',
  },
]

// Trending hashtags
export const trendingHashtags = [
  '#عقارات_مصر',
  '#شقق_للبيع',
  '#التجمع_الخامس',
  '#استثمار_عقاري',
  '#الساحل_الشمالي',
  '#إيجارات',
]

// Cities
export const egyptianCities = [
  'القاهرة',
  'الجيزة',
  'الإسكندرية',
  'القاهرة الجديدة',
  'الشيخ زايد',
  'مدينتي',
  'العاصمة الإدارية',
  'الساحل الشمالي',
  'العين السخنة',
]

// Property types
export const propertyTypes = [
  { value: 'apartment', label: 'شقة' },
  { value: 'villa', label: 'فيلا' },
  { value: 'studio', label: 'استوديو' },
  { value: 'duplex', label: 'دوبلكس' },
  { value: 'penthouse', label: 'بنتهاوس' },
  { value: 'land', label: 'أرض' },
  { value: 'office', label: 'مكتب' },
  { value: 'shop', label: 'محل' },
]
