/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrustRouteImport } from './routes/trust'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SearchRouteImport } from './routes/search'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as HelpRouteImport } from './routes/help'
import { Route as AboutRouteImport } from './routes/about'
import { Route as MeRouteRouteImport } from './routes/me/route'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MessagesIndexRouteImport } from './routes/messages/index'
import { Route as MeIndexRouteImport } from './routes/me/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as UIdRouteImport } from './routes/u.$id'
import { Route as PropertyIdRouteImport } from './routes/property.$id'
import { Route as MessagesThreadIdRouteImport } from './routes/messages/$threadId'
import { Route as MeTenanciesRouteImport } from './routes/me/tenancies'
import { Route as MeSettingsRouteImport } from './routes/me/settings'
import { Route as MeSavedRouteImport } from './routes/me/saved'
import { Route as MePreferencesRouteImport } from './routes/me/preferences'
import { Route as MeMatchesRouteImport } from './routes/me/matches'
import { Route as MeApplicationsRouteImport } from './routes/me/applications'
import { Route as ListNewRouteImport } from './routes/list/new'
import { Route as DashboardVerifyRouteImport } from './routes/dashboard/verify'
import { Route as DashboardReviewsRouteImport } from './routes/dashboard/reviews'
import { Route as DashboardModerationRouteImport } from './routes/dashboard/moderation'
import { Route as DashboardListingsRouteImport } from './routes/dashboard/listings'
import { Route as DashboardLeadsRouteImport } from './routes/dashboard/leads'
import { Route as AuthVerifyRouteImport } from './routes/auth/verify'
import { Route as AuthProfileRouteImport } from './routes/auth/profile'
import { Route as AuthLoginRouteImport } from './routes/auth/login'

const TrustRoute = TrustRouteImport.update({
  id: '/trust',
  path: '/trust',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRouteRoute = MeRouteRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesIndexRoute = MessagesIndexRouteImport.update({
  id: '/messages/',
  path: '/messages/',
  getParentRoute: () => rootRouteImport,
} as any)
const MeIndexRoute = MeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MeRouteRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const UIdRoute = UIdRouteImport.update({
  id: '/u/$id',
  path: '/u/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertyIdRoute = PropertyIdRouteImport.update({
  id: '/property/$id',
  path: '/property/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesThreadIdRoute = MessagesThreadIdRouteImport.update({
  id: '/messages/$threadId',
  path: '/messages/$threadId',
  getParentRoute: () => rootRouteImport,
} as any)
const MeTenanciesRoute = MeTenanciesRouteImport.update({
  id: '/tenancies',
  path: '/tenancies',
  getParentRoute: () => MeRouteRoute,
} as any)
const MeSettingsRoute = MeSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => MeRouteRoute,
} as any)
const MeSavedRoute = MeSavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => MeRouteRoute,
} as any)
const MePreferencesRoute = MePreferencesRouteImport.update({
  id: '/preferences',
  path: '/preferences',
  getParentRoute: () => MeRouteRoute,
} as any)
const MeMatchesRoute = MeMatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => MeRouteRoute,
} as any)
const MeApplicationsRoute = MeApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => MeRouteRoute,
} as any)
const ListNewRoute = ListNewRouteImport.update({
  id: '/list/new',
  path: '/list/new',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardVerifyRoute = DashboardVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardReviewsRoute = DashboardReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardModerationRoute = DashboardModerationRouteImport.update({
  id: '/moderation',
  path: '/moderation',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardListingsRoute = DashboardListingsRouteImport.update({
  id: '/listings',
  path: '/listings',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardLeadsRoute = DashboardLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const AuthVerifyRoute = AuthVerifyRouteImport.update({
  id: '/auth/verify',
  path: '/auth/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthProfileRoute = AuthProfileRouteImport.update({
  id: '/auth/profile',
  path: '/auth/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/me': typeof MeRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/help': typeof HelpRoute
  '/notifications': typeof NotificationsRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/terms': typeof TermsRoute
  '/trust': typeof TrustRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/profile': typeof AuthProfileRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/dashboard/leads': typeof DashboardLeadsRoute
  '/dashboard/listings': typeof DashboardListingsRoute
  '/dashboard/moderation': typeof DashboardModerationRoute
  '/dashboard/reviews': typeof DashboardReviewsRoute
  '/dashboard/verify': typeof DashboardVerifyRoute
  '/list/new': typeof ListNewRoute
  '/me/applications': typeof MeApplicationsRoute
  '/me/matches': typeof MeMatchesRoute
  '/me/preferences': typeof MePreferencesRoute
  '/me/saved': typeof MeSavedRoute
  '/me/settings': typeof MeSettingsRoute
  '/me/tenancies': typeof MeTenanciesRoute
  '/messages/$threadId': typeof MessagesThreadIdRoute
  '/property/$id': typeof PropertyIdRoute
  '/u/$id': typeof UIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/me/': typeof MeIndexRoute
  '/messages/': typeof MessagesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/help': typeof HelpRoute
  '/notifications': typeof NotificationsRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/terms': typeof TermsRoute
  '/trust': typeof TrustRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/profile': typeof AuthProfileRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/dashboard/leads': typeof DashboardLeadsRoute
  '/dashboard/listings': typeof DashboardListingsRoute
  '/dashboard/moderation': typeof DashboardModerationRoute
  '/dashboard/reviews': typeof DashboardReviewsRoute
  '/dashboard/verify': typeof DashboardVerifyRoute
  '/list/new': typeof ListNewRoute
  '/me/applications': typeof MeApplicationsRoute
  '/me/matches': typeof MeMatchesRoute
  '/me/preferences': typeof MePreferencesRoute
  '/me/saved': typeof MeSavedRoute
  '/me/settings': typeof MeSettingsRoute
  '/me/tenancies': typeof MeTenanciesRoute
  '/messages/$threadId': typeof MessagesThreadIdRoute
  '/property/$id': typeof PropertyIdRoute
  '/u/$id': typeof UIdRoute
  '/dashboard': typeof DashboardIndexRoute
  '/me': typeof MeIndexRoute
  '/messages': typeof MessagesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/me': typeof MeRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/help': typeof HelpRoute
  '/notifications': typeof NotificationsRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/terms': typeof TermsRoute
  '/trust': typeof TrustRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/profile': typeof AuthProfileRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/dashboard/leads': typeof DashboardLeadsRoute
  '/dashboard/listings': typeof DashboardListingsRoute
  '/dashboard/moderation': typeof DashboardModerationRoute
  '/dashboard/reviews': typeof DashboardReviewsRoute
  '/dashboard/verify': typeof DashboardVerifyRoute
  '/list/new': typeof ListNewRoute
  '/me/applications': typeof MeApplicationsRoute
  '/me/matches': typeof MeMatchesRoute
  '/me/preferences': typeof MePreferencesRoute
  '/me/saved': typeof MeSavedRoute
  '/me/settings': typeof MeSettingsRoute
  '/me/tenancies': typeof MeTenanciesRoute
  '/messages/$threadId': typeof MessagesThreadIdRoute
  '/property/$id': typeof PropertyIdRoute
  '/u/$id': typeof UIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/me/': typeof MeIndexRoute
  '/messages/': typeof MessagesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/me'
    | '/about'
    | '/help'
    | '/notifications'
    | '/privacy'
    | '/search'
    | '/terms'
    | '/trust'
    | '/auth/login'
    | '/auth/profile'
    | '/auth/verify'
    | '/dashboard/leads'
    | '/dashboard/listings'
    | '/dashboard/moderation'
    | '/dashboard/reviews'
    | '/dashboard/verify'
    | '/list/new'
    | '/me/applications'
    | '/me/matches'
    | '/me/preferences'
    | '/me/saved'
    | '/me/settings'
    | '/me/tenancies'
    | '/messages/$threadId'
    | '/property/$id'
    | '/u/$id'
    | '/dashboard/'
    | '/me/'
    | '/messages/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/help'
    | '/notifications'
    | '/privacy'
    | '/search'
    | '/terms'
    | '/trust'
    | '/auth/login'
    | '/auth/profile'
    | '/auth/verify'
    | '/dashboard/leads'
    | '/dashboard/listings'
    | '/dashboard/moderation'
    | '/dashboard/reviews'
    | '/dashboard/verify'
    | '/list/new'
    | '/me/applications'
    | '/me/matches'
    | '/me/preferences'
    | '/me/saved'
    | '/me/settings'
    | '/me/tenancies'
    | '/messages/$threadId'
    | '/property/$id'
    | '/u/$id'
    | '/dashboard'
    | '/me'
    | '/messages'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/me'
    | '/about'
    | '/help'
    | '/notifications'
    | '/privacy'
    | '/search'
    | '/terms'
    | '/trust'
    | '/auth/login'
    | '/auth/profile'
    | '/auth/verify'
    | '/dashboard/leads'
    | '/dashboard/listings'
    | '/dashboard/moderation'
    | '/dashboard/reviews'
    | '/dashboard/verify'
    | '/list/new'
    | '/me/applications'
    | '/me/matches'
    | '/me/preferences'
    | '/me/saved'
    | '/me/settings'
    | '/me/tenancies'
    | '/messages/$threadId'
    | '/property/$id'
    | '/u/$id'
    | '/dashboard/'
    | '/me/'
    | '/messages/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  MeRouteRoute: typeof MeRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  HelpRoute: typeof HelpRoute
  NotificationsRoute: typeof NotificationsRoute
  PrivacyRoute: typeof PrivacyRoute
  SearchRoute: typeof SearchRoute
  TermsRoute: typeof TermsRoute
  TrustRoute: typeof TrustRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthProfileRoute: typeof AuthProfileRoute
  AuthVerifyRoute: typeof AuthVerifyRoute
  ListNewRoute: typeof ListNewRoute
  MessagesThreadIdRoute: typeof MessagesThreadIdRoute
  PropertyIdRoute: typeof PropertyIdRoute
  UIdRoute: typeof UIdRoute
  MessagesIndexRoute: typeof MessagesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trust': {
      id: '/trust'
      path: '/trust'
      fullPath: '/trust'
      preLoaderRoute: typeof TrustRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/': {
      id: '/messages/'
      path: '/messages'
      fullPath: '/messages/'
      preLoaderRoute: typeof MessagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me/': {
      id: '/me/'
      path: '/'
      fullPath: '/me/'
      preLoaderRoute: typeof MeIndexRouteImport
      parentRoute: typeof MeRouteRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/u/$id': {
      id: '/u/$id'
      path: '/u/$id'
      fullPath: '/u/$id'
      preLoaderRoute: typeof UIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/property/$id': {
      id: '/property/$id'
      path: '/property/$id'
      fullPath: '/property/$id'
      preLoaderRoute: typeof PropertyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/$threadId': {
      id: '/messages/$threadId'
      path: '/messages/$threadId'
      fullPath: '/messages/$threadId'
      preLoaderRoute: typeof MessagesThreadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me/tenancies': {
      id: '/me/tenancies'
      path: '/tenancies'
      fullPath: '/me/tenancies'
      preLoaderRoute: typeof MeTenanciesRouteImport
      parentRoute: typeof MeRouteRoute
    }
    '/me/settings': {
      id: '/me/settings'
      path: '/settings'
      fullPath: '/me/settings'
      preLoaderRoute: typeof MeSettingsRouteImport
      parentRoute: typeof MeRouteRoute
    }
    '/me/saved': {
      id: '/me/saved'
      path: '/saved'
      fullPath: '/me/saved'
      preLoaderRoute: typeof MeSavedRouteImport
      parentRoute: typeof MeRouteRoute
    }
    '/me/preferences': {
      id: '/me/preferences'
      path: '/preferences'
      fullPath: '/me/preferences'
      preLoaderRoute: typeof MePreferencesRouteImport
      parentRoute: typeof MeRouteRoute
    }
    '/me/matches': {
      id: '/me/matches'
      path: '/matches'
      fullPath: '/me/matches'
      preLoaderRoute: typeof MeMatchesRouteImport
      parentRoute: typeof MeRouteRoute
    }
    '/me/applications': {
      id: '/me/applications'
      path: '/applications'
      fullPath: '/me/applications'
      preLoaderRoute: typeof MeApplicationsRouteImport
      parentRoute: typeof MeRouteRoute
    }
    '/list/new': {
      id: '/list/new'
      path: '/list/new'
      fullPath: '/list/new'
      preLoaderRoute: typeof ListNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/verify': {
      id: '/dashboard/verify'
      path: '/verify'
      fullPath: '/dashboard/verify'
      preLoaderRoute: typeof DashboardVerifyRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/reviews': {
      id: '/dashboard/reviews'
      path: '/reviews'
      fullPath: '/dashboard/reviews'
      preLoaderRoute: typeof DashboardReviewsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/moderation': {
      id: '/dashboard/moderation'
      path: '/moderation'
      fullPath: '/dashboard/moderation'
      preLoaderRoute: typeof DashboardModerationRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/listings': {
      id: '/dashboard/listings'
      path: '/listings'
      fullPath: '/dashboard/listings'
      preLoaderRoute: typeof DashboardListingsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/leads': {
      id: '/dashboard/leads'
      path: '/leads'
      fullPath: '/dashboard/leads'
      preLoaderRoute: typeof DashboardLeadsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/auth/verify': {
      id: '/auth/verify'
      path: '/auth/verify'
      fullPath: '/auth/verify'
      preLoaderRoute: typeof AuthVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/profile': {
      id: '/auth/profile'
      path: '/auth/profile'
      fullPath: '/auth/profile'
      preLoaderRoute: typeof AuthProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardLeadsRoute: typeof DashboardLeadsRoute
  DashboardListingsRoute: typeof DashboardListingsRoute
  DashboardModerationRoute: typeof DashboardModerationRoute
  DashboardReviewsRoute: typeof DashboardReviewsRoute
  DashboardVerifyRoute: typeof DashboardVerifyRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardLeadsRoute: DashboardLeadsRoute,
  DashboardListingsRoute: DashboardListingsRoute,
  DashboardModerationRoute: DashboardModerationRoute,
  DashboardReviewsRoute: DashboardReviewsRoute,
  DashboardVerifyRoute: DashboardVerifyRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

interface MeRouteRouteChildren {
  MeApplicationsRoute: typeof MeApplicationsRoute
  MeMatchesRoute: typeof MeMatchesRoute
  MePreferencesRoute: typeof MePreferencesRoute
  MeSavedRoute: typeof MeSavedRoute
  MeSettingsRoute: typeof MeSettingsRoute
  MeTenanciesRoute: typeof MeTenanciesRoute
  MeIndexRoute: typeof MeIndexRoute
}

const MeRouteRouteChildren: MeRouteRouteChildren = {
  MeApplicationsRoute: MeApplicationsRoute,
  MeMatchesRoute: MeMatchesRoute,
  MePreferencesRoute: MePreferencesRoute,
  MeSavedRoute: MeSavedRoute,
  MeSettingsRoute: MeSettingsRoute,
  MeTenanciesRoute: MeTenanciesRoute,
  MeIndexRoute: MeIndexRoute,
}

const MeRouteRouteWithChildren =
  MeRouteRoute._addFileChildren(MeRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  MeRouteRoute: MeRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  HelpRoute: HelpRoute,
  NotificationsRoute: NotificationsRoute,
  PrivacyRoute: PrivacyRoute,
  SearchRoute: SearchRoute,
  TermsRoute: TermsRoute,
  TrustRoute: TrustRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthProfileRoute: AuthProfileRoute,
  AuthVerifyRoute: AuthVerifyRoute,
  ListNewRoute: ListNewRoute,
  MessagesThreadIdRoute: MessagesThreadIdRoute,
  PropertyIdRoute: PropertyIdRoute,
  UIdRoute: UIdRoute,
  MessagesIndexRoute: MessagesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
