// Seed data for the Beitco mock store — demo properties and users.
// Pure data (no behavior); imported by store.ts. Swap for a real DB seed later.

import heroImg from "@/assets/hero-home.jpg";
import maadi from "@/assets/area-maadi.jpg";
import zayed from "@/assets/area-sheikh-zayed.jpg";
import alex from "@/assets/area-alexandria.jpg";
import newCairo from "@/assets/area-new-cairo.jpg";
import type { Property, User } from "./types";

export const seedProperties: Property[] = [
  {
    id: "1",
    ownerId: "u-mostafa",
    title: "شقة شمسها حلوة جنب الجامعة الأمريكية",
    area: "القاهرة الجديدة · التجمع الخامس",
    address: "محور التسعين الجنوبي، التجمع الخامس، القاهرة الجديدة",
    lat: 30.0235,
    lng: 31.4912,
    type: "شقة",
    status: "published",
    price: 18500,
    trust: 9.2,
    verified: true,
    reviewsCount: 24,
    residents: 6,
    internet: 9.4,
    image: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=600&h=400&fit=crop",
    images: [heroImg, newCairo, maadi, zayed],
    description:
      "شقة منوّرة وهادية بأوضتين، على بعد 8 دقايق من الجامعة الأمريكية. مفروشة بالكامل، نت فايبر، وكومباوند مؤمَّن بحراسة 24 ساعة. تنفع لعروسين أو لتنين زمايل شغل عايزين يشاركوا.",
    quality: { internet: 9.4, safety: 9.1, noise: 8.7, maintenance: 9.0, cleanliness: 9.3 },
    amenities: [
      "نت 200 ميجا",
      "تكييف",
      "غسالة",
      "ميكروويف",
      "تلاجة",
      "أسانسير",
      "جراج مغطى",
      "أمن 24 ساعة",
      "مفروشة",
    ],
    costs: [
      { label: "الإيجار", amount: 18500 },
      { label: "النت", amount: 450 },
      { label: "الكهربا (متوسط)", amount: 900 },
      { label: "المياه", amount: 120 },
      { label: "رسوم خدمة", amount: 350 },
    ],
    beds: { total: 4, available: 1, occupied: 3 },
    rentalMode: "whole",
    spec: { unitType: "شقة", bedrooms: 2, bathrooms: 2, floor: 3, sizeM2: 120, furnished: true },
    wholePrice: 18500,
    wholeStatus: "available",
    rooms: [
      {
        id: "1-r1",
        name: "الأوضة الرئيسية",
        features: ["تكييف", "حمام خاص", "بلكونة"],
        sizeM2: 24,
        beds: [],
      },
      { id: "1-r2", name: "الأوضة التانية", features: ["تكييف", "دولاب"], sizeM2: 16, beds: [] },
    ],
    nearby: [
      { id: "1-n1", type: "جامعة", name: "الجامعة الأمريكية", minutes: 8 },
      { id: "1-n2", type: "مول", name: "كايرو فيستيفال سيتي", minutes: 12 },
      { id: "1-n3", type: "سوبر ماركت", name: "كارفور", minutes: 5 },
    ],
    customSpecs: [
      { id: "1-c1", label: "اتجاه الشمس", value: "بحري - شرقي" },
      { id: "1-c2", label: "التشطيب", value: "سوبر لوكس" },
    ],
    landlord: {
      id: "u-mostafa",
      name: "مصطفى ح.",
      initials: "م.ح",
      trust: 9.4,
      responseRate: 97,
      verified: true,
    },
    reviews: [
      {
        id: "r1-1",
        propertyId: "1",
        author: "نور أ.",
        initials: "ن.أ",
        monthsLived: 11,
        rating: 9.4,
        date: "مارس 2026",
        body: "بصراحة من أهدى الشوارع في التجمع الخامس. النت ما بيقطعش وانت في الميتنجات، التكييف شغّال في كل الأوض، ومصطفى بيصلّح أي حاجة في يوم واحد.",
      },
      {
        id: "r1-2",
        propertyId: "1",
        author: "كريم س.",
        initials: "ك.س",
        monthsLived: 6,
        rating: 9.0,
        date: "يناير 2026",
        body: "السعر ممتاز بالنسبة للمنطقة. شوية دوشة يوم الجمعة بالليل بسبب الكافيه اللي قريب، بس عدا كده الشقة نضيفة جدًا والمكان آمن.",
      },
      {
        id: "r1-3",
        propertyId: "1",
        author: "ياسمين ر.",
        initials: "ي.ر",
        monthsLived: 14,
        rating: 9.6,
        date: "نوفمبر 2025",
        body: "قعدت هنا عقدين متتاليين. صاحب الشقة محترم ومش بيدخل من غير ما يقول، وعمّال العمارة محترفين.",
      },
    ],
    qa: [
      {
        id: "q1-1",
        propertyId: "1",
        asker: "عمر",
        answerer: "مصطفى ح. (صاحب الشقة)",
        date: "من أسبوعين",
        q: "النت بيبقى كويس قد إيه للميتنجات بالنهار؟",
        a: "فايبر 200/200. فيه ساكنين شغّالين ريموت طول اليوم من غير أي مشكلة.",
      },
      {
        id: "q1-2",
        propertyId: "1",
        asker: "سارة",
        date: "من 5 أيام",
        q: "فيه سوبر ماركت قريب نقدر نمشي له؟",
      },
    ],
    createdAt: "2025-09-01T00:00:00Z",
  },
  {
    id: "2",
    ownerId: "u-coliving",
    title: "أوضة مشتركة في المعادي",
    area: "المعادي · شارع 9",
    address: "شارع 9، المعادي، القاهرة",
    type: "سرير",
    status: "published",
    price: 3200,
    trust: 8.1,
    verified: true,
    reviewsCount: 32,
    residents: 8,
    internet: 8.4,
    image: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=600&h=400&fit=crop",
    images: [maadi, heroImg, newCairo, alex],
    description:
      "مكان لطلبة وشغّالين ريموت، على بعد مشي من كافيهات شارع 9 ومترو المعادي. مطبخ مشترك، ونضافة أسبوعية محسوبة في السعر.",
    quality: { internet: 8.4, safety: 8.6, noise: 7.4, maintenance: 8.0, cleanliness: 8.5 },
    amenities: ["نت 100 ميجا", "تكييف", "غسالة", "مطبخ مشترك", "نضافة أسبوعية", "مكان شغل"],
    costs: [
      { label: "إيجار السرير", amount: 3200 },
      { label: "الفواتير (شاملة)", amount: 0 },
      { label: "النضافة", amount: 0 },
    ],
    beds: { total: 8, available: 2, occupied: 6 },
    rentalMode: "by_bed",
    spec: { unitType: "شقة", bedrooms: 3, bathrooms: 2, floor: 2, sizeM2: 150, furnished: true },
    rooms: [
      {
        id: "2-r1",
        name: "الأوضة الكبيرة المكيّفة",
        features: ["تكييف", "بلكونة"],
        beds: [
          {
            id: "2-b1",
            label: "سرير 1",
            status: "reserved",
            price: 3500,
            occupant: {
              userId: "u-renter-ahmed",
              linkStatus: "confirmed",
              name: "أحمد سمير",
              phone: "+201111222333",
              moveInDate: "2026-07-01",
              notes: "دفع عربون نص شهر",
            },
          },
          { id: "2-b2", label: "سرير 2", status: "occupied", price: 3500 },
          {
            id: "2-b3",
            label: "سرير 3 (جنب الشباك)",
            status: "available",
            price: 3500,
            features: ["جنب الشباك"],
          },
        ],
      },
      {
        id: "2-r2",
        name: "أوضة الوسط",
        features: ["تكييف"],
        beds: [
          { id: "2-b4", label: "سرير 1", status: "occupied", price: 3200 },
          { id: "2-b5", label: "سرير 2", status: "occupied", price: 3200 },
          { id: "2-b6", label: "سرير 3", status: "occupied", price: 3200 },
        ],
      },
      {
        id: "2-r3",
        name: "الأوضة الصغيرة",
        features: [],
        beds: [
          { id: "2-b7", label: "سرير 1", status: "occupied", price: 2800 },
          { id: "2-b8", label: "سرير 2", status: "available", price: 2800 },
        ],
      },
    ],
    landlord: {
      id: "u-coliving",
      name: "بيتكو كولايفنج",
      initials: "ب.ك",
      trust: 8.6,
      responseRate: 92,
      verified: true,
    },
    reviews: [
      {
        id: "r2-1",
        propertyId: "2",
        author: "هنا م.",
        initials: "ه.م",
        monthsLived: 4,
        rating: 8.4,
        date: "أبريل 2026",
        body: "نضيف، الزمايل لطاف، والمكان جامد. بس بيبقى فيه شوية دوشة في الويك إند.",
      },
    ],
    qa: [],
    createdAt: "2025-11-15T00:00:00Z",
  },
  {
    id: "3",
    ownerId: "u-zayed",
    title: "سرير في كومباوند الشيخ زايد",
    area: "الشيخ زايد · الحي التاني",
    address: "الحي التاني، الشيخ زايد، الجيزة",
    type: "سرير",
    status: "published",
    price: 4500,
    trust: 8.8,
    verified: false,
    reviewsCount: 15,
    residents: 4,
    internet: 9.0,
    image: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=600&h=400&fit=crop",
    images: [zayed, heroImg, maadi, alex],
    description:
      "كومباوند هادي وآمن، مساحات خضرا، نوادي رياضية قريبة. السرير في أوضة لتنين مع زميل واحد. تنفع لشغّالين شركات.",
    quality: { internet: 9.0, safety: 9.2, noise: 8.5, maintenance: 8.7, cleanliness: 8.8 },
    amenities: ["نت 200 ميجا", "تكييف", "غسالة", "أسانسير", "أمن 24 ساعة", "حمام سباحة"],
    costs: [
      { label: "إيجار السرير", amount: 4500 },
      { label: "الكهربا والمياه", amount: 400 },
      { label: "النت", amount: 200 },
    ],
    beds: { total: 6, available: 3, occupied: 3 },
    rentalMode: "by_bed",
    rentToGender: "male_only",
    spec: { unitType: "شقة", bedrooms: 2, bathrooms: 1, floor: 4, sizeM2: 90, furnished: true },
    rooms: [
      {
        id: "3-r1",
        name: "أوضة مكيّفة بحمام خاص",
        features: ["تكييف", "حمام خاص"],
        beds: [
          { id: "3-b1", label: "سرير 1", status: "available", price: 4500 },
          { id: "3-b2", label: "سرير 2", status: "available", price: 4500 },
          { id: "3-b3", label: "سرير 3", status: "occupied", price: 4500 },
        ],
      },
      {
        id: "3-r2",
        name: "الأوضة العادية",
        features: ["دولاب"],
        beds: [
          { id: "3-b4", label: "سرير 1", status: "available", price: 3800 },
          { id: "3-b5", label: "سرير 2", status: "occupied", price: 3800 },
          { id: "3-b6", label: "سرير 3", status: "occupied", price: 4000 },
        ],
      },
    ],
    landlord: {
      id: "u-zayed",
      name: "أحمد ع.",
      initials: "أ.ع",
      trust: 8.5,
      responseRate: 88,
      verified: false,
    },
    reviews: [],
    qa: [],
    createdAt: "2026-01-10T00:00:00Z",
  },
  {
    id: "4",
    ownerId: "u-fam",
    title: "شقة عيلة في مدينة نصر",
    area: "مدينة نصر · عباس العقاد",
    address: "شارع عباس العقاد، مدينة نصر، القاهرة",
    lat: 30.0588,
    lng: 31.3401,
    type: "شقة",
    status: "published",
    price: 12000,
    trust: 7.9,
    verified: true,
    reviewsCount: 18,
    residents: 5,
    internet: 8.2,
    image: "https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=600&h=400&fit=crop",
    images: [heroImg, alex, maadi, zayed],
    description:
      "شقة 3 أوض في قلب عباس العقاد. قريبة من الميادين الرئيسية والمواصلات. تنفع لعيلة صغيرة.",
    quality: { internet: 8.2, safety: 8.0, noise: 6.8, maintenance: 7.9, cleanliness: 8.3 },
    amenities: ["نت 100 ميجا", "تكييف", "غسالة", "ميكروويف", "تلاجة", "أسانسير", "مفروشة"],
    costs: [
      { label: "الإيجار", amount: 12000 },
      { label: "النت", amount: 350 },
      { label: "الكهربا", amount: 700 },
    ],
    beds: { total: 3, available: 1, occupied: 2 },
    rentalMode: "whole",
    spec: { unitType: "شقة", bedrooms: 3, bathrooms: 2, floor: 5, sizeM2: 140, furnished: true },
    wholePrice: 12000,
    wholeStatus: "available",
    nightlyPrice: 850,
    rooms: [
      { id: "4-r1", name: "أوضة النوم الرئيسية", features: ["تكييف", "حمام خاص"], beds: [] },
      { id: "4-r2", name: "أوضة الأطفال", features: ["تكييف"], beds: [] },
      { id: "4-r3", name: "مكتب / أوضة ضيوف", features: ["دولاب"], beds: [] },
    ],
    landlord: {
      id: "u-fam",
      name: "هدى م.",
      initials: "ه.م",
      trust: 8.2,
      responseRate: 91,
      verified: true,
    },
    reviews: [],
    qa: [],
    createdAt: "2025-12-20T00:00:00Z",
  },
  {
    id: "5",
    ownerId: "u-students",
    title: "سكن طلبة جنب جامعة القاهرة",
    area: "الدقي · شارع التحرير",
    address: "شارع التحرير، الدقي، الجيزة",
    type: "سرير",
    status: "published",
    price: 2800,
    trust: 8.5,
    verified: true,
    reviewsCount: 42,
    residents: 10,
    internet: 8.8,
    image: "https://images.unsplash.com/photo-1554995207-c18c203602cb?w=600&h=400&fit=crop",
    images: [heroImg, maadi, newCairo, alex],
    description:
      "سكن طلبة منظّم، خمس دقايق من جامعة القاهرة. أسرّة في أوض لأربعة. مطبخ مشترك ومسؤول مقيم.",
    quality: { internet: 8.8, safety: 8.4, noise: 7.0, maintenance: 8.2, cleanliness: 8.7 },
    amenities: ["نت 150 ميجا", "تكييف", "غسالة", "مطبخ مشترك", "مسؤول مقيم"],
    costs: [
      { label: "إيجار السرير", amount: 2800 },
      { label: "الفواتير", amount: 0 },
    ],
    beds: { total: 10, available: 4, occupied: 6 },
    rentalMode: "by_bed",
    spec: { unitType: "شقة", bedrooms: 4, bathrooms: 2, floor: 6, sizeM2: 160, furnished: true },
    rooms: [
      {
        id: "5-r1",
        name: "أوضة 4 سراير مكيّفة",
        features: ["تكييف"],
        beds: [
          { id: "5-b1", label: "سرير 1", status: "occupied", price: 3000 },
          { id: "5-b2", label: "سرير 2", status: "occupied", price: 3000 },
          { id: "5-b3", label: "سرير 3", status: "occupied", price: 3000 },
          { id: "5-b4", label: "سرير 4", status: "available", price: 3000 },
        ],
      },
      {
        id: "5-r2",
        name: "أوضة 3 سراير",
        features: [],
        beds: [
          { id: "5-b5", label: "سرير 1", status: "occupied", price: 2800 },
          { id: "5-b6", label: "سرير 2", status: "available", price: 2800 },
          { id: "5-b7", label: "سرير 3", status: "occupied", price: 2800 },
        ],
      },
      {
        id: "5-r3",
        name: "أوضة 3 سراير",
        features: [],
        beds: [
          { id: "5-b8", label: "سرير 1", status: "available", price: 2800 },
          { id: "5-b9", label: "سرير 2", status: "available", price: 2800 },
          { id: "5-b10", label: "سرير 3", status: "occupied", price: 2800 },
        ],
      },
    ],
    nearby: [
      { id: "5-n1", type: "مترو", name: "البحوث", line: "الخط الثاني", minutes: 6 },
      { id: "5-n2", type: "جامعة", name: "جامعة القاهرة", minutes: 10 },
      { id: "5-n3", type: "مواصلات", name: "موقف الجيزة", minutes: 4 },
    ],
    customSpecs: [{ id: "5-c1", label: "النظام", value: "طلبة وموظفين بس" }],
    landlord: {
      id: "u-students",
      name: "سكن النيل",
      initials: "س.ن",
      trust: 8.7,
      responseRate: 95,
      verified: true,
    },
    reviews: [],
    qa: [],
    createdAt: "2025-08-01T00:00:00Z",
  },
  {
    id: "6",
    ownerId: "u-alex",
    title: "أوضة لوحدها في إسكندرية",
    area: "سموحة · شارع فوزي معاذ",
    address: "شارع فوزي معاذ، سموحة، إسكندرية",
    type: "أوضة",
    status: "published",
    price: 5500,
    trust: 8.3,
    verified: false,
    reviewsCount: 11,
    residents: 3,
    internet: 7.8,
    image: "https://images.unsplash.com/photo-1484154218962-a197022b5858?w=600&h=400&fit=crop",
    images: [alex, heroImg, maadi, zayed],
    description:
      "أوضة لوحدها في شقة هادية في سموحة. شغّالين معايا تنين بنات محترمات. تنفع لبنت شغالة أو طالبة.",
    quality: { internet: 7.8, safety: 8.5, noise: 8.1, maintenance: 7.9, cleanliness: 8.4 },
    amenities: ["نت 100 ميجا", "تكييف", "غسالة", "تلاجة", "مفروشة"],
    costs: [
      { label: "إيجار الأوضة", amount: 5500 },
      { label: "النت والكهربا", amount: 500 },
    ],
    beds: { total: 4, available: 2, occupied: 2 },
    rentalMode: "by_room",
    rentToGender: "female_only",
    spec: { unitType: "شقة", bedrooms: 4, bathrooms: 2, floor: 3, sizeM2: 175, furnished: true },
    rooms: [
      {
        id: "6-r1",
        name: "أوضة على البحر",
        features: ["تكييف", "حمام خاص", "بلكونة", "إطلالة بحر", "تراس خاص"],
        price: 6500,
        status: "available",
        beds: [],
      },
      {
        id: "6-r2",
        name: "أوضة كبيرة مكيّفة",
        features: ["تكييف", "دولاب"],
        price: 5500,
        status: "available",
        beds: [],
      },
      {
        id: "6-r3",
        name: "أوضة متوسطة",
        features: ["دولاب"],
        price: 4500,
        status: "occupied",
        beds: [],
      },
      { id: "6-r4", name: "أوضة صغيرة", features: [], price: 3800, status: "occupied", beds: [] },
    ],
    landlord: {
      id: "u-alex",
      name: "ليلى ج.",
      initials: "ل.ج",
      trust: 8.0,
      responseRate: 85,
      verified: false,
    },
    reviews: [],
    qa: [],
    createdAt: "2026-02-05T00:00:00Z",
  },
  {
    id: "7",
    ownerId: "u-mostafa",
    title: "شقة للبيع تشطيب سوبر لوكس في التجمع",
    area: "القاهرة الجديدة · التجمع الخامس",
    address: "جنوب الأكاديمية، التجمع الخامس، القاهرة الجديدة",
    type: "شقة",
    status: "published",
    price: 4200000,
    trust: 9.0,
    verified: true,
    reviewsCount: 0,
    residents: 0,
    internet: 8.5,
    image: "https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=600&h=400&fit=crop",
    images: [newCairo, heroImg, maadi, zayed],
    description:
      "شقة 165 متر، 3 غرف وريسبشن كبير، تشطيب سوبر لوكس بالكامل. الدور التالت بأسانسير، فيو على لاندسكيب، وقريبة من كل الخدمات. التمليك جاهز والشقة فاضية للمعاينة في أي وقت.",
    quality: { internet: 8.5, safety: 9.0, noise: 8.4, maintenance: 8.8, cleanliness: 9.0 },
    amenities: ["تكييف", "أسانسير", "جراج مغطى", "أمن 24 ساعة", "حديقة", "مفروشة"],
    costs: [],
    beds: { total: 1, available: 1, occupied: 0 },
    listingType: "sale",
    salePrice: 4200000,
    saleStatus: "available",
    negotiable: true,
    spec: { unitType: "شقة", bedrooms: 3, bathrooms: 2, floor: 3, sizeM2: 165, furnished: true },
    nearby: [
      { id: "7-n1", type: "مول", name: "داون تاون مول", minutes: 7 },
      { id: "7-n2", type: "جامعة", name: "الجامعة الأمريكية", minutes: 10 },
    ],
    customSpecs: [
      { id: "7-c1", label: "التشطيب", value: "سوبر لوكس" },
      { id: "7-c2", label: "نوع التمليك", value: "مسجّل" },
    ],
    landlord: {
      id: "u-mostafa",
      name: "مصطفى ح.",
      initials: "م.ح",
      trust: 9.4,
      responseRate: 97,
      verified: true,
    },
    reviews: [],
    qa: [],
    createdAt: "2026-05-20T00:00:00Z",
  },
];

export const seedUsers: User[] = [
  {
    id: "u-admin",
    phone: "+201000000000",
    name: "فريق بيتكو",
    role: "both",
    trust: 9.9,
    verified: true,
    isAdmin: true,
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "u-mostafa",
    phone: "+201001234567",
    name: "مصطفى حسن",
    role: "owner",
    trust: 9.4,
    verified: true,
    createdAt: "2024-06-01T00:00:00Z",
  },
  // Sample renters so owners can search & link a real account when recording occupancy.
  {
    id: "u-renter-ahmed",
    phone: "+201111222333",
    name: "أحمد سمير",
    role: "renter",
    trust: 7.2,
    verified: true,
    createdAt: "2025-02-10T00:00:00Z",
  },
  {
    id: "u-renter-mona",
    phone: "+201222333444",
    name: "منى خالد",
    role: "renter",
    trust: 6.8,
    verified: false,
    createdAt: "2025-03-15T00:00:00Z",
  },
  {
    id: "u-renter-omar",
    phone: "+201001239876",
    name: "عمر فاروق",
    role: "renter",
    trust: 8.1,
    verified: true,
    createdAt: "2025-01-05T00:00:00Z",
  },
  {
    id: "u-renter-sara",
    phone: "+201155667788",
    name: "سارة إبراهيم",
    role: "renter",
    trust: 7.9,
    verified: true,
    createdAt: "2025-04-20T00:00:00Z",
  },
  {
    id: "u-renter-youssef",
    phone: "+201099887766",
    name: "يوسف ناصر",
    role: "renter",
    trust: 6.4,
    verified: false,
    createdAt: "2025-05-01T00:00:00Z",
  },
];
