import { User, Post, Listing, Comment, Conversation, NotificationItem, Group } from './types';

export const currentUser: User = {
  id: 'user-1',
  name: 'أحمد محمود',
  avatar: 'https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg',
  bio: 'مهتم بالعقارات والاستثمار العقاري',
  city: 'القاهرة',
  role: 'buyer',
  tier: 3,
  isVerified: true,
  followersCount: 1250,
  followingCount: 342,
  postsCount: 28,
  rating: 4.8,
  ratingCount: 127,
};

export const users: User[] = [
  {
    id: 'user-2',
    name: 'سارة علي',
    avatar: 'https://images.pexels.com/photos/415829/pexels-photo-415829.jpeg',
    bio: 'وسيط عقاري محترف',
    city: 'الجيزة',
    role: 'agent',
    tier: 2,
    isVerified: true,
    followersCount: 3500,
    followingCount: 215,
    postsCount: 156,
    rating: 4.9,
    ratingCount: 542,
  },
  {
    id: 'user-3',
    name: 'محمد الشرقاوي',
    avatar: 'https://images.pexels.com/photos/91227/pexels-photo-91227.jpeg',
    bio: 'باحث عن شقة أحلامي',
    city: 'القاهرة الجديدة',
    role: 'buyer',
    tier: 1,
    isVerified: false,
    followersCount: 234,
    followingCount: 456,
    postsCount: 12,
  },
  {
    id: 'user-4',
    name: 'فاطمة العبدالله',
    avatar: 'https://images.pexels.com/photos/1181690/pexels-photo-1181690.jpeg',
    bio: 'بائع عقار بخبرة 10 سنوات',
    city: 'الإسكندرية',
    role: 'seller',
    tier: 2,
    isVerified: true,
    followersCount: 892,
    followingCount: 123,
    postsCount: 45,
  },
];

export const listings: Listing[] = [
  {
    id: 'listing-1',
    title: 'شقة فاخرة في التجمع الخامس',
    type: 'apartment',
    status: 'for_sale',
    price: 1500000,
    location: 'التجمع الخامس',
    city: 'القاهرة',
    bedrooms: 3,
    bathrooms: 2,
    area: 150,
    image: 'https://images.pexels.com/photos/1457842/pexels-photo-1457842.jpeg',
    image2: 'https://images.pexels.com/photos/1643383/pexels-photo-1643383.jpeg',
    description: 'شقة حديثة بتشطيب عالي الجودة في موقع مميز بالقرب من جميع الخدمات',
    agent: users[0],
  },
  {
    id: 'listing-2',
    title: 'فيلا فخمة بحي الشرقية',
    type: 'villa',
    status: 'for_sale',
    price: 3500000,
    location: 'الشرقية',
    city: 'الجيزة',
    bedrooms: 4,
    bathrooms: 3,
    area: 300,
    image: 'https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg',
    agent: users[1],
  },
  {
    id: 'listing-3',
    title: 'استوديو جديد في وسط البلد',
    type: 'studio',
    status: 'for_rent',
    price: 2500,
    location: 'وسط البلد',
    city: 'القاهرة',
    bedrooms: 1,
    bathrooms: 1,
    area: 45,
    image: 'https://images.pexels.com/photos/2121121/pexels-photo-2121121.jpeg',
    agent: users[2],
  },
];

export const posts: Post[] = [
  {
    id: 'post-1',
    author: users[1],
    content: 'عقار جديد رائع للبيع في موقع متميز جداً. السعر تنافسي جداً ويستحق الاستثمار!',
    image: listings[0].image,
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000),
    likesCount: 324,
    commentsCount: 28,
    isLiked: false,
    isSaved: false,
    listing: listings[0],
  },
  {
    id: 'post-2',
    author: users[0],
    content: 'أنا شخصياً بدي أشتري شقة في منطقة آمنة برضه جودة البناء عالية. أي توصيات؟',
    createdAt: new Date(Date.now() - 5 * 60 * 60 * 1000),
    likesCount: 156,
    commentsCount: 42,
    isLiked: true,
    isSaved: false,
  },
  {
    id: 'post-3',
    author: users[1],
    content: 'هل تعرفون حي المقطم؟ أفضل حي للاستثمار العقاري الآن حسب رأيي الشخصي',
    createdAt: new Date(Date.now() - 8 * 60 * 60 * 1000),
    likesCount: 542,
    commentsCount: 89,
    isLiked: false,
    isSaved: true,
  },
];

export const comments: Comment[] = [
  {
    id: 'comment-1',
    author: users[2],
    content: 'سعر جداً منطقي، المنطقة آمنة وفيها كل الخدمات',
    createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000),
    likesCount: 45,
    isLiked: false,
    isPinned: true,
  },
  {
    id: 'comment-2',
    author: users[3],
    content: 'هل هناك إمكانية للتقسيط؟',
    createdAt: new Date(Date.now() - 3 * 60 * 60 * 1000),
    likesCount: 12,
    isLiked: false,
  },
];

export const conversations: Conversation[] = [
  {
    id: 'conv-1',
    participantId: 'user-2',
    participantName: 'سارة علي',
    participantAvatar: users[1].avatar,
    lastMessage: 'نعم، الشقة متاحة غداً للزيارة',
    lastMessageTime: new Date(Date.now() - 5 * 60 * 1000),
    unreadCount: 2,
    listing: listings[0],
  },
  {
    id: 'conv-2',
    participantId: 'user-3',
    participantName: 'محمد الشرقاوي',
    participantAvatar: users[2].avatar,
    lastMessage: 'شكراً على المساعدة، سأتواصل معك قريباً',
    lastMessageTime: new Date(Date.now() - 2 * 60 * 60 * 1000),
    unreadCount: 0,
  },
];

export const notifications: NotificationItem[] = [
  {
    id: 'notif-1',
    type: 'like',
    actor: [users[0], users[1]],
    content: 'و8 آخرين أعجبوا ببوستك',
    relatedPostId: 'post-1',
    createdAt: new Date(Date.now() - 10 * 60 * 1000),
    isRead: false,
  },
  {
    id: 'notif-2',
    type: 'comment',
    actor: users[2],
    content: 'علق على بوستك: "سعر جداً منطقي"',
    relatedPostId: 'post-1',
    createdAt: new Date(Date.now() - 30 * 60 * 1000),
    isRead: false,
  },
  {
    id: 'notif-3',
    type: 'follow',
    actor: users[3],
    content: 'بدأت متابعتك',
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000),
    isRead: true,
  },
];

export const groups: Group[] = [
  {
    id: 'group-1',
    name: 'محبي العقارات في مصر',
    description: 'مجموعة متخصصة في نقاش العقارات والاستثمار',
    coverImage: 'https://images.pexels.com/photos/1957478/pexels-photo-1957478.jpeg',
    membersCount: 15420,
    postsCount: 3256,
    isJoined: true,
  },
  {
    id: 'group-2',
    name: 'وسطاء العقار المحترفين',
    description: 'مجموعة خاصة بالوسطاء والمحترفين',
    coverImage: 'https://images.pexels.com/photos/2375694/pexels-photo-2375694.jpeg',
    membersCount: 8920,
    postsCount: 1850,
    isJoined: false,
  },
];
